- name: OGC:error
  subtype: service
  filters:
      # a variety of error options based on versions
    ors: 
      # - type: simple
      #   object: content
      #   value: 'http://www.opengis.net/ogc'
      - type: simple
        object: content
        value: 'ServiceExceptionReport'
      - type: simple
        object: content
        value: 'ExceptionReport'
      - type: simple
        object: content
        value: 'http://schemas.opengis.net/ows/1.0.0/owsExceptionReport.xsd'
  versions:
    checks:
      ors:
        - type: xpath
          # fully qualified xpath which is lovely and short here
          value: '@version'
- name: OGC:WMS
  subtype: service
  filters:
    ors:
      - type: simple
        object: content
        value: 'http://www.opengis.net/wms'
      - type: simple
        object: content
        value: '<!DOCTYPE WMT_MS_Capabilities SYSTEM "http://schemas.opengis.net/wms/1.1.1/WMS_MS_Capabilities.dtd"'
  service_description:
    - name: GetCapabilities
      filters:
        ors:
            # we are assuming that we are starting with a 
            # correctly identified wxs response
          - type: simple
            object: url
            value: 'REQUEST=GETCAPABILITIES'
          - type: simple
            object: content
            value: '<GetCapabilities>'
          - type: simple
            object: content
            value: 'name="GetCapabilities"'
  datasets:
  metadatas:
  versions:
    checks:
      ors:
        - type: xpath
          # fully qualified xpath which is lovely and short here
          value: '@version'
- name: OGC:WMTS
  subtype: service
  filters:
    ors:
      - type: simple
        object: content
        value: 'http://www.opengis.net/wmts'
      - type: simple
        object: content
        value: 'Operation name="GetTile"'
  service_description:
    - name: GetCapabilities
      filters:
        ors:
            # we are assuming that we are starting with a 
            # correctly identified wxs response
          - type: simple
            object: url
            value: 'REQUEST=GETCAPABILITIES'
          - type: simple
            object: content
            value: '<GetCapabilities>'
          - type: simple
            object: content
            value: 'name="GetCapabilities"'
  datasets:
  metadatas:
  versions:
    checks:
      ors:
        - type: xpath
          # fully qualified xpath which is lovely and short here
          value: '@version'
- name: OGC:SOS
  subtype: service
  filters:
    ors:
      - type: simple
        object: content
        value: 'http://www.opengis.net/sos'
      - type: simple
        object: content
        value: 'Operation name="DescribeSensor"'
  service_description:
    - name: GetCapabilities
      filters:
        ors:
            # we are assuming that we are starting with a 
            # correctly identified wxs response
          - type: simple
            object: url
            value: 'REQUEST=GETCAPABILITIES'
          - type: simple
            object: content
            value: '<GetCapabilities>'
          - type: simple
            object: content
            value: 'name="GetCapabilities"'
  datasets:
  metadatas:
  versions:
    checks:
      ors:
        - type: xpath
          # fully qualified xpath which is lovely and short here
          value: '@version'
- name: OGC:WFS
  subtype: service
  filters:
    ors:
      - type: simple
        object: content
        value: 'http://www.opengis.net/wfs'
  service_description:
    - name: GetCapabilities
      filters:
        ors:
          - type: simple
            object: url
            value: 'REQUEST=GETCAPABILITIES'
          - type: simple
            object: content
            value: '<GetCapabilities>'
          - type: simple
            object: content
            value: 'name="GetCapabilities"'
  datasets:
    - name: GetFeature
      filters:
        ors:
            # 1.0.0
          - type: complex
            operator: ands
            filters:
              - type: simple
                object: content
                value: '<GetFeature>'
              - type: simple
                object: content
                value: '<FeatureTypeList>'
            # 1.1.0
          - type: complex
            operator: ands
            filters:
              - type: simple
                object: content
                value: '<ows:Operation name="GetFeature">'
              - type: simple
                object: content
                value: '<FeatureTypeList>'
  metadatas:
    # contains a link to a metadata url (we don't care 
    # about parentage at this point)
    filters:
      ors:
        - type: xpath
          value: '/*/{http://www.opengis.net/wfs}FeatureTypeList/{http://www.opengis.net/wfs}FeatureType/{http://www.opengis.net/wfs}MetadataURL'

  versions:
    checks:
      ors:
        - type: xpath
          # fully qualified xpath which is lovely and short here
          value: '@version'
- name: OGC:WCS
  subtype: service
  filters:
    ors:
      - type: simple
        object: content
        value: 'http://www.opengis.net/wcs'
  service_description:
    - name: GetCapabilities
      filters:
        ors:
          - type: simple
            object: url
            value: 'REQUEST=GETCAPABILITIES'
          - type: simple
            object: content
            value: '<GetCapabilities>'
          - type: simple
            object: content
            value: 'name="GetCapabilities"'
  datasets:
    - name: GetCoverage
      filters:
        ors:
            # 1.0.0
          - type: complex
            operator: ands
            filters:
              - type: simple
                object: content
                value: '<GetCoverage>'
              - type: simple
                object: content
                value: '<CoverageOfferingBrief>'
            # 1.1.2
          - type: complex
            operator: ands
            filters:
              - type: simple
                object: content
                value: '<ows:Operation name="GetCoverage">'
              - type: simple
                object: content
                value: '<CoverageSummary>'
  metadatas:
    # wcs 1.0.0 has no metadata url
    # filter for 1.1.2
    filters:
      ors:
        - type: xpath
          value: '/*/{http://www.opengis.net/wcs}Contents/{http://www.opengis.net/wcs}ContentSummary/{http://www.opengis.net/ows}Metadata'
  versions:
    checks:
      ors:
        - type: xpath
          # fully qualified xpath which is lovely and short here
          value: '@version'
- name: OGC:CSW
  subtype: service
  filters:
    ors:
      # - type: simple
      #   object: content
      #   value: 'http://www.opengis.net/cat/csw'
      - type: complex
        operator: ands
        filters:
          - type: simple
            object: content
            value: 'http://www.opengis.net/cat/csw'
          - type: simple
            object: content
            value: '<csw:Capabilities'
      - type: complex
        operator: ands
        filters:
          - type: simple
            object: content
            value: 'http://www.opengis.net/cat/csw'
          - type: simple
            object: url
            value: 'SERVICE=CSW'
  service_description:
    - name: GetCapabilities
      filters:
        ors:
          - type: simple
            object: url
            value: 'REQUEST=GETCAPABILITIES'
          - type: simple
            object: content
            value: '<GetCapabilities>'
          - type: simple
            object: content
            value: 'name="GetCapabilities"'
  datasets:
  metadatas:
  versions:
    checks:
      ors:
        - type: xpath
          # fully qualified xpath which is lovely and short here
          value: '@version'